### ISSUE TITLE
pyne 0.5

### ISSUE THREAD

**Issue by skc222** [skc222/1st_repository#3]
```
ubuntu@ubuntu:~/Downloads/pyne-0.5.0$ python setup.py install --user
Downloading http://data.pyne.io/decay.tar.gz
/usr/bin/cmake
CMake command is
cmake .. -DHAVE_SETUPTOOLS=TRUE -DPYTHON_EXECUTABLE=/usr/bin/python
-- The Fortran compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working Fortran compiler: /usr/bin/f95
-- Check for working Fortran compiler: /usr/bin/f95  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /usr/bin/f95 supports Fortran 90
-- Checking whether /usr/bin/f95 supports Fortran 90 -- yes
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_Fortran_IMPLICIT_LINK_DIRECTORIES = /usr/lib/gcc/x86_64-linux-gnu/5;/usr/lib/x86_64-linux-gnu;/usr/lib;/lib/x86_64-linux-gnu;/lib
-- CMAKE_Fortran_IMPLICIT_LINK_LIBRARIES = gfortran;m;quadmath;m;c
-- Build type: Release
-- Found HDF5: debug;/usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5_hl.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so;optimized;/usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5_hl.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so  
-- HDF5_LIBRARY_DIRS = /usr/lib/x86_64-linux-gnu/hdf5/serial
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so
-- PYTHON_EXECUTABLE: /usr/bin/python
-- Could NOT find MOAB (missing:  MOAB_LIBRARY MOAB_INCLUDE_DIR) 
-- MOAB Found: FALSE
-- Found Cython: /usr/bin/cython  
-- Cython Version: Cython version 0.23.4
-- Pyne platform defined as: __LINUX__
CMAKE_Fortran_COMPILER full path: /usr/bin/f95
Fortran compiler: f95
No optimized Fortran compiler flags are known, we just try -O2...

                                  /   \       
                          )      ((   ))     (                          
(@)                      /|\      ))_((     /|\                          
|-|                     / | \    (/\|/\)   / | \                      (@) 
| | -------------------/--|-voV---\`|'/--Vov-|--\---------------------|-|
|-|                         '^`   (o o)  '^`                          | |
| |                               `\Y/'                               |-|
|-|                                                                   | |
| |        /\             ___           __  __             /\         |-|
|-|       /^~\           / _ \_   _  /\ \ \/__\           /^~\        | |  
| |       /^~\          / /_)/ | | |/  \/ /_\             /^~\        |-|
|-|       /^~\         / ___/| |_| / /\  //__             /^~\        | | 
| |       ^||`         \/     \__, \_\ \/\__/             ^||`        |-|  
|-|        ||                |____/                        ||         | | 
| |       ====                                            ====        |-|
|-|                                                                   | |
| |                                                                   |-|
|-|___________________________________________________________________| |
(@)              l   /\ /         ( (       \ /\   l                `\|-|
                 l /   V           \ \       V   \ l                  (@)
                 l/                _) )_          \I                   
                                   `\ /'
                                     `  


-- CMake Install Prefix: /usr/local
-- RPATH: $ORIGIN/../lib
-- NUMPY_VERSION_STRING = 1.12.1
-- Found Numpy: 1.12.1  
-- Include paths for /home/ubuntu/Downloads/pyne-0.5.0/src: /usr/include/hdf5/serial;/home/ubuntu/.local/lib/python2.7/site-packages/numpy/core/include;/home/ubuntu/Downloads/pyne-0.5.0/src
-- Include paths for /home/ubuntu/Downloads/pyne-0.5.0/pyne: /usr/include/hdf5/serial;/home/ubuntu/.local/lib/python2.7/site-packages/numpy/core/include;/home/ubuntu/Downloads/pyne-0.5.0/src
CMake Warning (dev) at pyne/CMakeLists.txt:154 (target_link_libraries):
  Policy CMP0039 is not set: Utility targets may not have link dependencies.
  Run "cmake --help-policy CMP0039" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Utility target "transport_spatial_methods" should not be used as the target
  of a target_link_libraries call.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Include paths for /home/ubuntu/Downloads/pyne-0.5.0/pyne/xs: /usr/include/hdf5/serial;/home/ubuntu/.local/lib/python2.7/site-packages/numpy/core/include;/home/ubuntu/Downloads/pyne-0.5.0/src;/usr/include/python2.7
-- Include paths for /home/ubuntu/Downloads/pyne-0.5.0: /usr/include/hdf5/serial;/home/ubuntu/.local/lib/python2.7/site-packages/numpy/core/include
-- Copying C/C++ header files.
-- Copying Cython header files.
-- Copying scripts.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/Downloads/pyne-0.5.0/build
Scanning dependencies of target ReplicatePythonSourceTree
[  0%] Built target ReplicatePythonSourceTree
Scanning dependencies of target pyne
[  1%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/invar.f90.o
[  2%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/solvar.f90.o
[  3%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/precision_module.f90.o
[  4%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/geompack.f90.o
[  5%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/trackstruct.f90.o
[  6%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/timevar.f90.o
[  7%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/igeompack.f90.o
[  8%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/trackroutines.f90.o
[  9%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/sct_module.f90.o
[ 10%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/dgfem_kernel.f90.o
[ 11%] Building Fortran object src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/ahotn_kernel_module.f90.o
/home/ubuntu/Downloads/pyne-0.5.0/src/transport_spatial_methods/3d/ahotn_kernel_module.f90:281:132:

 x*ez-36.0d0*alpha1)*dxz/ex + (ey*ez-36.0d0*beta1 )*dyz/ey ) + 3.0d0*gamma0*ez0 
                                                                             1
Error: Line truncated at (1) [-Werror=line-truncation]
/home/ubuntu/Downloads/pyne-0.5.0/src/transport_spatial_methods/3d/ahotn_kernel_module.f90:282:132:

 x*ey-36.0d0*alpha1)*dxy/ex + (ey*ez-36.0d0*gamma1)*dzy/ez ) + 3.0d0*beta0 *ey0 
                                                                             1
Error: Line truncated at (1) [-Werror=line-truncation]
/home/ubuntu/Downloads/pyne-0.5.0/src/transport_spatial_methods/3d/ahotn_kernel_module.f90:283:132:

 ex*ey-36.0d0*beta1 )*dyx/ey + (ex*ez-36.0d0*gamma1)*dzx/ez ) + 3.0d0*alpha0*ex0
                                                                              1
Error: Line truncated at (1) [-Werror=line-truncation]
f951: some warnings being treated as errors
src/CMakeFiles/pyne.dir/build.make:398: recipe for target 'src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/ahotn_kernel_module.f90.o' failed
make[3]: *** [src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/ahotn_kernel_module.f90.o] Error 1
src/CMakeFiles/pyne.dir/build.make:414: recipe for target 'src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/ahotn_kernel_module.f90.o.provides' failed
make[2]: *** [src/CMakeFiles/pyne.dir/transport_spatial_methods/3d/ahotn_kernel_module.f90.o.provides] Error 2
CMakeFiles/Makefile2:122: recipe for target 'src/CMakeFiles/pyne.dir/all' failed
make[1]: *** [src/CMakeFiles/pyne.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

--------------------

If you are having issues building pyne, please report your problem to pyne-dev@googlegroups.com or look for help at http://pyne.io

--------------------
Traceback (most recent call last):
  File "setup.py", line 449, in <module>
    main()
  File "setup.py", line 421, in main
    main_safe(cmake_args, make_args)
  File "setup.py", line 413, in main_safe
    main_body(cmake_args, make_args)
  File "setup.py", line 393, in main_body
    rtn = subprocess.check_call(['make'] + make_args, cwd='build')
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2
ubuntu@ubuntu:~/Downloads/pyne-0.5.0$ 

```

**Comment by katyhuff** [comment]
Definitely try a new ubuntu build. BUT, I wouldn't be surprised if this is an actual bug in the ahot/3d code. Specifically, it looks like those lines are too long. The default line truncation in fortran is 132 characters. The ampersands are continuation syntax. If you include all characters in that line (281) of the ahotn_kernel_module.f90 file, I think the number of characters is 135 or so. 

Can you please move this issue to the pyne repository? I think it is a real issue and should be discussed there.

**Comment by skc222** [comment]
Okay. I will create an issue regarding this there if I get this error even after fresh rebuild.
Thank you!
